server:
  port: 8080

spring:
  application:
    name: springboot_shopping
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        show_sql: false
        format_sql: false

api:
  email:
    url: http://localhost:8081
    api-key: EMAIL_API_KEY
  push:
    url: http://localhost:8082
    api-key: PUSH_API_KEY

decorator:
  datasource:
    p6spy:
      enable-logging: true